# Mod Properties
archives_base_name = TEMPLATE_ARCHIVES_NAME
maven_group = TEMPLATE_MAVEN_GROUP
mod_version = 1.0.0

# Minecraft & Fabric
minecraft_version=TEMPLATE_MC_VERSION
yarn_mappings=TEMPLATE_YARN_MAPPINGS
loader_version=TEMPLATE_LOADER_VERSION
fabric_version=TEMPLATE_FABRIC_VERSION

# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true